### ISSUE TITLE
2.01 update gives error in Polisy

### ISSUE THREAD

**Issue by macjeff** [bpaauwe/udi-darksky-poly#2]
I know it was made for PGC but it comes up as update in Polisy and when you run it you get an error.   

So can you either remove the update from Polisy (go back to 2.0 for polisy if possible) or issue a 2.02 that works. 

I have 2.0 installed so OK for now but I bet if a new person tries to install 2.01 they will get the error.

thanks

**Comment by bpaauwe** [comment]
If it's the update that's failing, that's a problem with Polyglot on the Polisy, not the node server. I don't have any control over the update process. 

If it's the node server itself that's failing, I'll need more information on how it's failing as it's working fine on my Polisy.

**Comment by macjeff** [comment]
UDI found bug but for now I had to uninstall and reinstall and its ok now.
