### ISSUE TITLE
Request- Sunrise/Sunset tomorrow

### ISSUE THREAD

**Issue by macjeff** [bpaauwe/udi-darksky-poly#3]
ISY can allow you to put the Sunrise and Sunset time from today into an email but NOT tomorrow though you can get tomorrow data in seconds in ISY programs.

Dark Sky has that data I think.  Could you add it?

I did a forum post about the ISY.  I think after sunrise on a specific day it should show tomorrows.  At 3pm if I look at sunrise I want to see tomorrow not what happened this AM but the ISY shows today still.

https://forum.universal-devices.com/topic/28827-sunrise-time-question/

**Comment by bpaauwe** [comment]
ISY node values can only be numeric. Thus I would only be able to add the sunrise/sunset times darksky in seconds so you'd still have the same problem of it not being in a human readable date/time format.

**Comment by macjeff** [comment]
I can use this command from the TimeData node to get the day of week

${sys.node.n014_timedata.GV5}

and if I change GV5 to GV10 I can get the season like Winter.

and my alarm system I can get all the Zone Names that come in like Front Door, Living Room Window, etc.

and from DarkSky I can get Rain or Partly Cloudy and put that right into email.

How are those getting in as Text not numbers that I can put into email?   

My guess is there are key words that ISY has built in that they can convert to like the days of the week or months in the year.

So only other option is to convert seconds to actual time in AM/PM format.   

Jeff

**Comment by bpaauwe** [comment]
The ISY can have a fixed lookup list to convert numbers to text.  So for things that have a well defined number = text mapping, it can do that.  But seconds to date/time is not something that can be mapped. The mapping has to be pre-computed and does take up memory in the ISY so to map a few million second to date/time values would kill the ISY.

This is why the time node servers split it up so there are separate values for hour, minute, day, month, year.  It's easy enough to map months 1-12 to their names, but you can't have a single value that looks like "02/12/2002 12:34pm".

This is something that has been requested as many node servers could make use of a value that was in seconds, but automatically gets translated to a human readable date/time when displayed (or included in an email).

**Comment by macjeff** [comment]
FYI I am not attacking you on this if it seemed that way. 

I just like to understand and you have done a great job of explaining.

Thanks!!!

Jeff

**Comment by macjeff** [comment]
This was added to timeserver
