### ISSUE TITLE
Fields request for DarkSky Data

### ISSUE THREAD

**Issue by macjeff** [bpaauwe/udi-darksky-poly#4]
Climate module going away.  I noticed some of the things it has like Wind Speed tomorrow is not in your node.  This is what I get every day in email.  I can map to Dark Sky if you have these fields.

Weather Today 

High Temp -    35 F 
Humidity-   48 %
Condition -    20
Cloud Condition-   3
Rain Today-    0 inches
Snow Today-   0 inches
Precip Intensity-  1
Wind Today-   4 mph
Wind Gust so far-  15 mph

Weather Tomorrow

Low Temp-    27 F
High Temp -    37 F
Humidity-   45 %
Condition -    0
Cloud Condition-   2
Rain Tomorrow-  0 inches
Snow Tomorrow-  0 inches
Precip Intensity-  0
Wind Tomorrow-  6 mph
Wind Gust tomorrow- 16 mph

**Comment by macjeff** [comment]
can you add more fields or is this all they provide?

**Comment by bpaauwe** [comment]
I can add some of those.   Darksky doesn't separate out snow/rain values and provide daily totals, just current intensity. It also doesn't provide a gust so far, just the current wind gust value.  

I can add wind and precip intensity to the forecast.

**Comment by macjeff** [comment]
Thats fine.  Let me know if you need testing or I will watch for the update on Polisy.

**Comment by memphis2k** [comment]
> 
> 
> I can add some of those. Darksky doesn't separate out snow/rain values and provide daily totals, just current intensity. It also doesn't provide a gust so far, just the current wind gust value.
> 
> I can add wind and precip intensity to the forecast.

Any chance on adding Sunrise & Sunset?  Two things I'm missing from the Climate module.
Thanks,

**Comment by macjeff** [comment]
I would also like sunrise and sunset, and I am not trying to take away from this node-server but there is one called TimeData that already has Sunrise and Sunset for today and tomorrow.

**Comment by macjeff** [comment]
new version looks awesome-  thanks!!!
