### ISSUE TITLE
UV Index the same every day

### ISSUE THREAD

**Issue by macjeff** [bpaauwe/udi-darksky-poly#5]
I noticed the UV index is the same for forecast 0-7.

Always a 3.   Even if its cloudy or sunny.

**Comment by bpaauwe** [comment]
That's probably what DarkSky is sending. The node server doesn't do any manipulation of the data that comes from DarkSky.   Check it by going to Darksky directly or you can check the node server log when debug logging is enabled, the node server will log everything it gets from DarkSky or let me know the location you're using and I can try it.

**Comment by macjeff** [comment]
I was wrong it does change but it does not match.  With that said Dark Sky has the UV index by hour so if you check at a certain hour you might get a different number.  They also show the highest for the day.  
I used the exact same Lat and Long.   https://darksky.net/details/39.1524,-77.6669/2020-2-20/us12/en

So its pretty close.  Seems like only forecast day one is off this week.  Not sure why.

Wait...last week the days were all 1, 2 and 3 on dark sky.   ISY showed all 3.  Could it be an issue showing less than 3 but if its 3 or greater it is correct?  That would explain all of last week and also 2/20.  

Date     Dark Sky         ISY
2/20       2                    3
2/21       3                     3
2/22      4                     4
2/23       4                    4
2/34       3                     3

**Comment by macjeff** [comment]
So if nothing you can do you can go ahead and close this
